### ISSUE TITLE
Verify if the custom hash is a empty string

### ISSUE THREAD

**Issue by Michael-Liendo** [whizzes/quicklink#34]
I can create a link with the hash `""`
should comprobate the hash
![image](https://user-images.githubusercontent.com/70660410/219872459-07edae7a-3e71-4d98-ab34-8333e7e1a043.png)

**Comment by EstebanBorai** [comment]
@Michael-Liendo Nice catch! Thanks so much!

**Comment by EstebanBorai** [comment]
@benjamingb is taking care of this issue.

**Comment by benjamingb** [comment]
Sending PR

**Comment by EstebanBorai** [comment]
Current version on `main` ensures this doesnt happens anymore!
